### ISSUE TITLE
Show AVV catalogue JSON

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-parse-cloud#24]
As a MiBi-Portal Admin I would like to see the JSON text after having uploaded an AVV catalogue XML into the dashboard.

**Comment by birgitlewicki** [comment]
The JSON text of an uploaded catalogue can be seen in the dashboard.
This was implemented with #22 and #21

**Comment by afalenski** [comment]
The AVV JSON can be viewed in Dashboard column 'catalogueData'. The user can pull the cell large to display up to 13 entries and have a look at more by scrolling down.
Done.
______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Browsers:
- Firefox 128.4.0esr (64-Bit)
